### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by nextgenthemes** [bripkens/project-sidebar#9]
This is as close to brackets behaviour as I could find. Actually better since brackets had no real projects but just a list of last used folders, also nice but AFAIK it not supports projects with multiple folders defined.

To me this would be perfect if there would be a project switcher inside the normal sidebar or a just a extra "Projects" menu for that, not sure of this is possible in Atom. The extra sidebar is taking up screen space for a thing that not necessary need to be in my view all the time, well at least not inside its own sidebar.

Also there should be a option ot have the sidebar opened by default. Every time I close Atom its gone. The default shortcut is not working for me right now, probably conflict with another addon.

There is the "List Projects" from project manager, but I really hate the open new window behavior of Atom so I am glad this project solves this. Again a simple new menu would be awsome, if you have nothing better to do and that is possible ;)

Since the sidebar is fixed size and as wide as the longest project name you can trick it into being small by having very short project names, for the time being this is what I do.

**Comment by bripkens** [comment]
Hey @nextgenthemes,

I am glad to hear that you find this plugin useful. Currently, I am busy with other open source work, but feel free to add this yourself. Most of your requests should be easy to add and I'd happy to merge them into the project. If you want to, I can give you some guidance w.r.t. the docs and the project structure.

Cheers

Ben

**Comment by nextgenthemes** [comment]
Not sure if I want to get into how to extend Atom right now, I am not that into JavaScript. I just hoped it may be a piece of cake to just add a menu that behaves like the sidebar, not opening a new window.

You know if Atom even provides a API to add a new root menu? Or to add something to the main sidebar? I have a feeing there is not.

Also the project manager has this "close current" option that is "currently disabled ... because broken ... w8ing for better implementation". My question is, how did you handle this here? Maybe that would be useful there as well.

I would like a menu more then pressing a shortcut but I guess I just wait for that option to work, then I do not need this plugin anymore for fast project witching without ending up with multiple windows open.

**Comment by mehcode** [comment]
@nextgenthemes Check out https://atom.io/packages/project-plus

**Comment by nextgenthemes** [comment]
Thanks, I already uninstalled _project sidebar_ the bug I mentioned in _project manager_ has been fixed. I hit shift+strg+p now to switch projects and it auto closes the window and opens a new one. From the look at _project-plus_ it seems similar. Also I have projects with multiple folders, I guess the no "config file, no mess" thing would be not working like that.

**Comment by mehcode** [comment]
> Also I have projects with multiple folders, I guess the no "config file, no mess" thing would be not working like that.

It does fully support multiple folders. And it switches in the same window (fast enough that we can tab through projects faster than your OS can tab through your open windows).

Atom was already tracking your open projects -- this package just reads where atom saved that information and lets you switch around. So if you had a previously open project with multiple folders -- it should just work.
